Repository acmutd/TrackIT, pull requests merged in 2020-04, with the labels that each got.

#8 feature/add-new-workshop
  src/Components/Admin/AdminAuth.js
  src/Components/Admin/AdminDashboard.js
  src/Components/Layout/ConfirmationDialog.js
  src/Components/Layout/NavBar.js
  src/Components/Workshop/CardTile.js
  src/Components/Workshop/Workshop.js
  src/Components/Workshop/WorkshopBar.js
  src/Components/Workshop/WorkshopEdit.js
  src/Components/Workshop/WorkshopLevelBar.js
Labels: enhancement, frontend

#26 Update Navbar Links
  src/App.js
  src/Components/Layout/NavBar.js
  src/Components/Pages/Pricing.js
  src/assets/acm-fav.png
  src/index.css
Labels: bug, frontend

#27 update/refine-admin-page
  package-lock.json
  package.json
  src/Components/Admin/AdminDashboard.js
  src/Components/Workshop/Workshop.js
  src/Components/Workshop/WorkshopBar.js
  src/Components/Workshop/WorkshopEdit.js
  src/Components/Workshop/WorkshopLevelBar.js
  src/index.js
Labels: backend, bug, dependencies, frontend

#30 fix/edit-date
  src/Components/Workshop/WorkshopEdit.js
Labels: bug

#32 feature/404-page
  src/App.js
  src/Components/Pages/Error404.js
  src/assets/404.png
Labels: enhancement, frontend

#31 feature/user-database-read
  package-lock.json
  src/App.js
  src/Components/Admin/Admin.js
  src/Components/Admin/AdminAuth.js
  src/Components/User/User.js
  src/Components/User/UserAuth.js
  src/Components/User/UserDash.js
  src/Components/User/WorkshopLogin.js
Labels: backend, bug, enhancement

#34 internal/heroku-configuration
  package-lock.json
  package.json
Labels: dependencies
