Repository acmutd/TrackIT, pull requests merged in 2020-07, with the labels that each got.

#82 update/code-ql
  .github/workflows/codeql-analysis.yml
Labels: internal

#81 feature/setup-redux-integrate-auth0
  .github/workflows/nodejs.yml
  firebase.json
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/admin/admin.ts
  functions/src/auth/auth.ts
  functions/src/index.ts
  functions/tsconfig.json
  functions/tslint.json
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/Components/Admin/Admin.test.tsx
  src/Components/Admin/Admin.tsx
  src/Components/Admin/AdminDashboard.tsx
  src/Components/Admin/__snapshots__/Admin.test.tsx.snap
  src/Components/Config/firebase.ts
  src/Components/Layout/NavBar.tsx
  src/Components/Pages/LandingPage.tsx
  src/Components/User/User.tsx
  src/Components/User/UserDash.tsx
  src/Components/User/UserWelcome.tsx
  src/Components/User/WorkshopLogin.tsx
  src/Components/Workshop/Workshop.tsx
  src/__snapshots__/App.test.tsx.snap
  src/actions/authentication.ts
  src/actions/user.ts
  src/index.tsx
  src/reducers/authentication.ts
  src/reducers/rootReducer.ts
  src/reducers/user.ts
  src/store/store.ts
Labels: backend, enhancement

#88 fix/user-dash-wrong-page
  src/Components/Layout/WorkshopEditor.tsx
  src/auth_views/Admin.tsx
  src/auth_views/User.tsx
  src/components/Layout/WorkshopEditor.tsx
  src/views/LandingPage.tsx
  src/views/UserDash.tsx
Labels: bug
