Repository acmutd/TrackIT, pull requests merged in 2020-05, with the labels that each got.

#37 Feature/admin database read
  src/App.js
  src/Components/Admin/Admin.js
  src/Components/Admin/AdminAuth.js
  src/Components/Admin/AdminDashboard.js
  src/Components/Layout/NavBar.js
  src/Components/User/User.js
  src/Components/User/UserAuth.js
  src/Components/User/UserDash.js
  src/Components/User/WorkshopLogin.js
  src/Components/Workshop/Workshop.js
  src/Components/Workshop/WorkshopBar.js
  src/Components/Workshop/WorkshopEdit.js
  src/Components/Workshop/WorkshopLevelBar.js
Labels: backend, enhancement, frontend

#38 fix/deletion-error
  src/Components/Admin/Admin.js
  src/Components/Admin/AdminAuth.js
  src/Components/Admin/AdminDashboard.js
  src/Components/User/User.js
  src/Components/User/UserAuth.js
  src/Components/User/WorkshopLogin.js
Labels: bug

#39 yml config for CI/CD
  .github/workflows/nodejs.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/App.test.js
  src/setupTests.js
Labels: dependencies, documentation, internal, test

#41 internal/documentation
  README.md
  src/Components/Admin/Admin.js
  src/Components/Admin/AdminAuth.js
  src/Components/Admin/AdminDashboard.js
  src/Components/Layout/ConfirmationDialog.js
  src/Components/Layout/NavBar.js
  src/Components/Pages/Error404.js
  src/Components/Pages/Pricing.js
  src/Components/User/User.js
  src/Components/User/UserAuth.js
  src/Components/User/UserDash.js
  src/Components/User/WorkshopLogin.js
  src/Components/Workshop/CardTile.js
  src/Components/Workshop/StudentBar.js
  src/Components/Workshop/Workshop.js
  src/Components/Workshop/WorkshopBar.js
  src/Components/Workshop/WorkshopEdit.js
  src/Components/Workshop/WorkshopLevelBar.js
Labels: documentation, internal

#42 fix/snapshot-listeners
  README.md
  handbook.md
  src/Components/Admin/Admin.js
  src/Components/Admin/AdminDashboard.js
  src/Components/Layout/Loading.js
  src/Components/User/User.js
  src/Components/User/UserDash.js
  src/Components/User/UserProgressBar.js
  src/Components/User/UserWelcome.js
  src/Components/Workshop/Workshop.js
Labels: backend, bug, documentation, enhancement, frontend

#43 feature/workshop-download
  package-lock.json
  package.json
  src/Components/Admin/AdminDashboard.js
  src/Components/Layout/NavBar.js
  src/Components/Workshop/WorkshopBar.js
Labels: dependencies, enhancement

#44 internal/final-changes
  src/Components/Admin/AdminDashboard.js
  src/Components/Workshop/CardTile.js
  src/Components/Workshop/Workshop.js
  src/Components/Workshop/WorkshopLevelBar.js
  src/assets/canvasjs.min.js
Labels: bug, good first issue, internal

#46 hotfix/colors-issue
  src/Components/User/UserDash.js
Labels: bug

#47 update/responsive-design
  src/Components/Admin/AdminDashboard.js
  src/Components/Workshop/CardTile.js
  src/Components/Workshop/StudentBar.js
  src/Components/Workshop/Workshop.js
  src/Components/Workshop/WorkshopBar.js
  src/Components/Workshop/WorkshopLevelBar.js
Labels: frontend, good first issue

#48 feature/content-editor
  package-lock.json
  package.json
  src/Components/Admin/AdminAuth.js
  src/Components/Layout/WorkshopEditor.js
  src/Components/User/UserAuth.js
  src/Components/User/UserDash.js
  src/Components/User/WorkshopLogin.js
  src/Components/Workshop/WorkshopEdit.js
  src/Components/Workshop/WorkshopLevelBar.js
  src/index.css
Labels: dependencies, frontend

#49 update/editing-alert
  package-lock.json
  src/App.js
  src/Components/Admin/Admin.js
  src/Components/Admin/AdminDashboard.js
  src/Components/Firebase/firebase.js
  src/Components/User/User.js
  src/Components/User/UserDash.js
  src/Components/User/WorkshopLogin.js
  src/Components/Workshop/WorkshopEdit.js
Labels: frontend

#50 feature/landing-page
  src/App.js
  src/Components/Layout/NavBar.js
  src/Components/Pages/LandingPage.js
Labels: frontend

#60 Interfaces created
  src/Components/Admin/Admin.tsx
  src/Components/Admin/AdminDashboard.tsx
  src/Components/Firebase/interface.ts
Labels: backend, internal

#52 update/typescript-pages
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Admin/AdminDashboard.tsx
  src/Components/Firebase/interface.ts
  src/Components/Layout/ConfirmationDialog.tsx
  src/Components/Layout/NavBar.tsx
  src/Components/Layout/WorkshopEditor.tsx
  src/Components/Pages/Error404.tsx
  src/Components/Pages/LandingPage.tsx
  src/Components/Pages/Pricing.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: internal

#65 update/typescript-workshop
  src/Components/Workshop/CardTile.tsx
  src/Components/Workshop/StudentBar.tsx
  src/Components/Workshop/Workshop.tsx
  src/Components/Workshop/WorkshopBar.tsx
  src/Components/Workshop/WorkshopEdit.tsx
  src/Components/Workshop/WorkshopLevelBar.tsx
Labels: internal

#63 update/typescript-user
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Admin/Admin.tsx
  src/Components/Admin/AdminAuth.tsx
  src/Components/Admin/AdminDashboard.tsx
  src/Components/Firebase/interface.ts
  src/Components/Layout/ConfirmationDialog.tsx
  src/Components/Layout/NavBar.tsx
  src/Components/Layout/WorkshopEditor.tsx
  src/Components/Pages/Error404.tsx
  src/Components/Pages/LandingPage.tsx
  src/Components/Pages/Pricing.tsx
  src/Components/User/User.tsx
  src/Components/User/UserAuth.tsx
  src/Components/User/UserDash.tsx
  src/Components/User/UserProgressBar.tsx
  src/Components/User/UserWelcome.tsx
  src/Components/User/WorkshopLogin.tsx
  src/Components/Workshop/CardTile.tsx
  src/Components/Workshop/StudentBar.tsx
  src/Components/Workshop/Workshop.tsx
  src/Components/Workshop/WorkshopBar.tsx
  src/Components/Workshop/WorkshopEdit.tsx
  src/Components/Workshop/WorkshopLevelBar.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: internal
